### ISSUE TITLE
Pretrained weight file 

### ISSUE THREAD

**Issue by abhigoku10** [zifyloo/SSAN#2]
@zifyloo  Thanks for sharing the code base  can you please share the pretrained weight file on google drive or one drive 

THanking you in advance

**Comment by abhigoku10** [comment]
@zifyloo  any update on this ? 

i tried to train the model with the source code on V100 machine with 16gb memory but after 6/8 epochs the terminal kills itself without any error ? 
I tried changing the batchsize from 64 to 4 and num_workers from 3 to 1 even after this i am getting error ? 

Please share ur thoughts

**Comment by zifyloo** [comment]
> 

We just use the resnet-50  model pretrained on the ImageNet database.

**Comment by zifyloo** [comment]
> @zifyloo any update on this ?
> 
> i tried to train the model with the source code on V100 machine with 16gb memory but after 6/8 epochs the terminal kills itself without any error ? I tried changing the batchsize from 64 to 4 and num_workers from 3 to 1 even after this i am getting error ?
> 
> Please share ur thoughts

Do you have any logs before it kill itself ? Maybe you can use breakpoint to debug.
