### ISSUE TITLE
Cross domain code

### ISSUE THREAD

**Issue by xmu-xiaoma666** [zifyloo/SSAN#3]
Thank you for your good job.
I find you have conducted the experiment for cross domain dataset.
Can you share the code for  cross domain training?

**Comment by zifyloo** [comment]
We use the same project  to hadle the cross-domain situation. You just need to change the train set and the test set for this project. Our spliting strategy of  the CUHK-PEDES in the cross-domain situation follows the paper 'Cross-Modal Cross-Domain Moment Alignment Network for Person Search'

**Comment by xmu-xiaoma666** [comment]
Thank you for your response. However, I can not find 'SSM' and 'VIPER' folder in your shared CUHK-PEDES dataset, I can only find CUHK03, CUHK01 and Market-1501 folder. Besides, there are 4 addtional folder i.e., cam_a, cam_b, test_query, train_query. I would like to know to how to correspond these folders with data.
If possible, can we communicate through WeChat？ My wechat ID is mayiwei1998.
Thanks,
Best wishes,
Yiwei Ma.

**Comment by zifyloo** [comment]
I will update this project for  the cross-domain situation mentioned in our paper in this weekend.

**Comment by xmu-xiaoma666** [comment]
That is great. Thank you very much.

**Comment by xmu-xiaoma666** [comment]
Do I need to download CUHK-PEDES datasets in other formats for cross-domain training？

**Comment by zifyloo** [comment]
No，just using the CUHK-PEDES datasets  according to the origin of its image.

**Comment by xmu-xiaoma666** [comment]
Well, I'm looking forward to your open source code. Will you open source today?

**Comment by zifyloo** [comment]
Sorry, I can't find the original data-processing file for the cross-domain. Accutally,  cam_a, and cam_b  belong to viper database.  test_query and train_query belong to the SSM database.

**Comment by zifyloo** [comment]
你就按着我文件目录下面的dataset/process_CUHK_data.py改就好，只是加了个判断来划分他的数据来源，最后你可以的得到五个域的训练集和测试集。

**Comment by xmu-xiaoma666** [comment]
好的好的，谢谢您
