### ISSUE TITLE
Request ICFG-PEDES dataset download

### ISSUE THREAD

**Issue by xbdxwyh** [zifyloo/SSAN#4]
Hi, thanks for your open-source work. It is a very attractive work. I would now like to reproduce the corresponding experimental results. Therefore, I have sent you an email requesting the download. Thank you very much for your help!

**Comment by zifyloo** [comment]
Do you send the mail to the chxding@scut.edu.cn ? Do he reply to you ? If not, please leave your email address.

**Comment by xbdxwyh** [comment]
Yes, he has written back to me, thanking you again for your open source work.

**Comment by zifyloo** [comment]
冲鸭小伙子，有任何问题留言给我哈。

**Comment by znithx** [comment]
作者你好，我们目前也在进行reid方面的研究，希望可以获得你们的ICFG-PEDES数据集进行实验，这是我的 邮箱 manzhang1@whu.edu.cn   、非常感谢！

**Comment by Nozomi1215** [comment]
作者你好，我正在进行Text-to-Image ReID方面的研究，希望可以获得你们的ICFG-PEDES数据集进行实验，我的邮箱是[zhenglh6@mail2.sysu.edu.cn](mailto:zhenglh6@mail2.sysu.edu.cn) 、非常感谢！

**Comment by promotesd** [comment]
作者你好，我正在进行Text-to-Image ReID方面的研究，希望可以获得你们的ICFG-PEDES数据集进行实验，我的邮箱是[832204116@fzu.edu.cn](mailto:832204116@fzu.edu.cn)非常感谢！

**Comment by li468441680-debug** [comment]
作者你好，我同样也在进行Text-to-Image ReID方面的研究，希望可以获得你们的ICFG-PEDES数据集进行实验，我的邮箱是作者你好，我正在进行Text-to-Image ReID方面的研究，希望可以获得你们的ICFG-PEDES数据集进行实验，我的邮箱是107552504878@stu.xju.edu.cn非常感谢！
