### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by yangwj21** [zifyloo/SSAN#5]
I sent email a week ago but haven't got a reply by now.

**Comment by zifyloo** [comment]
sorry for the late reply， please send the e-mail to eezhifenglin@mail.scut.edu.cn to request the dataset.

**Comment by belzx** [comment]
是不是作者不怎么看邮箱~~

**Comment by huranLi** [comment]
可以发一份数据集吗救救孩子

**Comment by yangwj21** [comment]
> 可以发一份数据集吗救救孩子

要征得作者同意，还得签一个agreement，我不太方便私自发><.
