### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by lyy9206** [zifyloo/SSAN#9]
I have sent an email to the specified email address two weeks ago, but there has been no reply.  Could you please tell me how to obtain the ICFG-PEDES dataset?

**Comment by lemontree893** [comment]
I have the same question.

**Comment by zifyloo** [comment]
sorry for the late reply, email 272521211@qq.com to get the dataset.

**Comment by XiaominZhang111** [comment]
i will be deeply grateful if anyone else send me ICFG-PEDES dataset at 1368542445@qq.com
